#!/bin/bash

if [ $# -ne 1 ]; then
	echo "Please, provide your server's FQDN as an argument";
	exit 1;
fi 

set -ex

openssl genrsa -aes256 -out ca-key.pem 2048
openssl req -new -x509 -days 365 -key ca-key.pem -sha256 -out ca.pem
openssl genrsa -out server-key.pem 2048
openssl req -subj "/CN=$1" -new -key server-key.pem -out server.csr
echo subjectAltName = IP:10.10.10.20,IP:127.0.0.1 > extfile.cnf
openssl x509 -req -days 365 -in server.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out server-cert.pem -extfile extfile.cnf
openssl genrsa -out key.pem 2048
openssl req -subj '/CN=client' -new -key key.pem -out client.csr
echo extendedKeyUsage = clientAuth > extfile.cnf
openssl x509 -req -days 365 -in client.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out cert.pem -extfile extfile.cnf
sudo rm -v client.csr server.csr
sudo chmod -v 0400 ca-key.pem key.pem server-key.pem
sudo chmod -v 0444 ca.pem server-cert.pem cert.pem
sudo mkdir -pv ~/.docker
sudo cp -v {ca,cert,key}.pem ~/.docker

echo "Please, make sure you set the following environment variables:"
echo "    * DOCKER_HOST=tcp://yourserverdomain:2376" 
echo "    * DOCKER_TLS_VERIFY=1"