#!/bin/bash

node_version=0.10.39
npm_version=2.11.3

if [ $# -ne 0 ]; then
	# User chose a version
	node_version=$1
fi

set -xe

#curl -SLO "https://nodejs.org/dist/v$node_version/node-v$node_version-linux-x64.tar.gz" \
#	&& curl -SLO "https://nodejs.org/dist/v$node_version/SHASUMS256.txt.asc" \
#	&& gpg --verify SHASUMS256.txt.asc \
#	&& grep " node-v$node_version-linux-x64.tar.gz\$" SHASUMS256.txt.asc | sha256sum -c - \
#	&& tar -xzf "node-v$node_version-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
#	&& rm "node-v$node_version-linux-x64.tar.gz" SHASUMS256.txt.asc \
#	&& npm install -g npm@"$npm_version" \
#	&& npm cache clear

sudo apt-get update
sudo apt-get install -y build-essential
sudo apt-get install -y libssl-dev

sudo apt-get install -y python-software-properties
sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install -y nodejs
